
version: '3'
services:
  web:
    build: .
    container_name: coding-garden-meower
    restart: always
    ports:
    - "5000:5000"
    - "8080:8080"
    volumes:
    - ./init:/usr/src/app/init
    - ./client:/usr/src/app/client
    - ./server:/usr/src/app/server
    links:
    - mongo
    environment:
    - MONGO_URI=mongo/meower
    - API_URL=http://localhost:5000
  mongo:
    image: mongo
    container_name: coding-garden-meower-db
